--
-- PostgreSQL database dump
--

\restrict RCEeyjGBklMRa3ipMk7VGzSpfdxrLsYCJBccAb4gFG8KeMcwXoCuGBS3KWexehJ

-- Dumped from database version 17.6
-- Dumped by pg_dump version 17.6

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: Actores; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Actores" (
    id integer NOT NULL,
    "Nombre" character varying(255),
    "Apellido" character varying(255),
    "Peliculas" character varying(255)
);


ALTER TABLE public."Actores" OWNER TO postgres;

--
-- Name: Actores_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Actores" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Actores_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Elenco; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Elenco" (
    id integer NOT NULL
);


ALTER TABLE public."Elenco" OWNER TO postgres;

--
-- Name: Elenco_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Elenco" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Elenco_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Peliculas; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Peliculas" (
    id integer NOT NULL,
    "Nombre" character varying(255),
    "Fecha de lanzamiento" date,
    "Duracion" time without time zone
);


ALTER TABLE public."Peliculas" OWNER TO postgres;

--
-- Name: Peliculas_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Peliculas" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Peliculas_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: Actores; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Actores" (id, "Nombre", "Apellido", "Peliculas") FROM stdin;
\.


--
-- Data for Name: Elenco; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Elenco" (id) FROM stdin;
\.


--
-- Data for Name: Peliculas; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Peliculas" (id, "Nombre", "Fecha de lanzamiento", "Duracion") FROM stdin;
\.


--
-- Name: Actores_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Actores_id_seq"', 1, false);


--
-- Name: Elenco_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Elenco_id_seq"', 1, false);


--
-- Name: Peliculas_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Peliculas_id_seq"', 1, false);


--
-- Name: Actores Actores_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Actores"
    ADD CONSTRAINT "Actores_pkey" PRIMARY KEY (id);


--
-- Name: Elenco Elenco_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Elenco"
    ADD CONSTRAINT "Elenco_pkey" PRIMARY KEY (id);


--
-- Name: Peliculas Peliculas_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Peliculas"
    ADD CONSTRAINT "Peliculas_pkey" PRIMARY KEY (id);


--
-- Name: Actores Actores_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Actores"
    ADD CONSTRAINT "Actores_id_fkey" FOREIGN KEY (id) REFERENCES public."Peliculas"(id);


--
-- Name: Actores Actores_id_fkey1; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Actores"
    ADD CONSTRAINT "Actores_id_fkey1" FOREIGN KEY (id) REFERENCES public."Elenco"(id);


--
-- Name: Peliculas Peliculas_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Peliculas"
    ADD CONSTRAINT "Peliculas_id_fkey" FOREIGN KEY (id) REFERENCES public."Elenco"(id);


--
-- PostgreSQL database dump complete
--

\unrestrict RCEeyjGBklMRa3ipMk7VGzSpfdxrLsYCJBccAb4gFG8KeMcwXoCuGBS3KWexehJ

