--
-- PostgreSQL database dump
--

\restrict I0Cs3S5rdUmtqeTHtHNwyQ5BbNWXrAcMhDolD9i1hb39t9oP5sABIgdd9afTqB6

-- Dumped from database version 17.6
-- Dumped by pg_dump version 17.6

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: Aplicacion; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Aplicacion" (
    id integer NOT NULL,
    "Nombre" character varying(255),
    "Version" numeric,
    "Plataforma" character varying(255)
);


ALTER TABLE public."Aplicacion" OWNER TO postgres;

--
-- Name: Aplicacion_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Aplicacion" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Aplicacion_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Publicaciones; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Publicaciones" (
    id integer NOT NULL,
    "Titulo" character varying(255),
    "Contenido" character varying(255),
    "Fecha de oublicacion" date
);


ALTER TABLE public."Publicaciones" OWNER TO postgres;

--
-- Name: Publicaciones_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Publicaciones" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Publicaciones_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Usuario; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Usuario" (
    id integer NOT NULL,
    "Nombre" character varying(255) NOT NULL,
    "Fecha de registro" date NOT NULL,
    "Email" character varying(255)
);


ALTER TABLE public."Usuario" OWNER TO postgres;

--
-- Name: Usuario_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Usuario" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Usuario_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: Aplicacion; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Aplicacion" (id, "Nombre", "Version", "Plataforma") FROM stdin;
\.


--
-- Data for Name: Publicaciones; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Publicaciones" (id, "Titulo", "Contenido", "Fecha de oublicacion") FROM stdin;
\.


--
-- Data for Name: Usuario; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Usuario" (id, "Nombre", "Fecha de registro", "Email") FROM stdin;
\.


--
-- Name: Aplicacion_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Aplicacion_id_seq"', 1, false);


--
-- Name: Publicaciones_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Publicaciones_id_seq"', 1, false);


--
-- Name: Usuario_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Usuario_id_seq"', 1, false);


--
-- Name: Aplicacion Aplicacion_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Aplicacion"
    ADD CONSTRAINT "Aplicacion_pkey" PRIMARY KEY (id);


--
-- Name: Publicaciones Publicaciones_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Publicaciones"
    ADD CONSTRAINT "Publicaciones_pkey" PRIMARY KEY (id);


--
-- Name: Usuario Usuario_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Usuario"
    ADD CONSTRAINT "Usuario_pkey" PRIMARY KEY (id);


--
-- Name: Publicaciones_index_0; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "Publicaciones_index_0" ON public."Aplicacion" USING btree (id);


--
-- Name: Publicaciones Publicaciones_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Publicaciones"
    ADD CONSTRAINT "Publicaciones_id_fkey" FOREIGN KEY (id) REFERENCES public."Usuario"(id);


--
-- Name: Publicaciones Publicaciones_id_fkey1; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Publicaciones"
    ADD CONSTRAINT "Publicaciones_id_fkey1" FOREIGN KEY (id) REFERENCES public."Aplicacion"(id);


--
-- Name: Usuario Usuario_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Usuario"
    ADD CONSTRAINT "Usuario_id_fkey" FOREIGN KEY (id) REFERENCES public."Aplicacion"(id);


--
-- PostgreSQL database dump complete
--

\unrestrict I0Cs3S5rdUmtqeTHtHNwyQ5BbNWXrAcMhDolD9i1hb39t9oP5sABIgdd9afTqB6

